---
layout: post
title: "Sapiens: A Brief History of Humankind" by Yuval Noah Harari 
---

A master piece. The author seems the history of the world with such clarity and worthy of re-reading. For a simple example, it describes the agricultural revolution, and asks us - are humans domesticated plants, or plants domesticated humans? Before the agricultural revolution, nomadic humankind probably ate a richer diet, and saw more interesting domains. After that, humankind are tied to a simple living hut, ate simple grain with little variation... With hindsight, we might say this is a symbiotic biosphere after the agricultural revolution. (Hahari gives credit to Richard Dawkins.) But his way to flip the table and see the world in this different perspective is what set this book apart from the rest.

One thing I found interesting -- the author noticed that the more sophisticated historians dig into history, the less certain they are, of whether the event is preordained to happen, and why it happened. They are less likely to pin down historic development to simple factors, and they are less certain it will happen at all.

Contrast historian's humble uncertainty about what happened in the past -- to the author's conviction that sapiens will disappear in the future, that bionic, cyborg... other forms of living being will be inevitable. Fascinating contrast. Perhaps the author holds that common view of economic recession -- not a question of whether it will happen, but when? As long as you don't pin down a date, the prediction will always be correct at some point in time? 

How is it related to other books? Besides giving credits to Richard Dawkins, when the book discussed the fateful encounter between Pizarro and the Incan emperor Atahualpa, its description of the events is eerily similar to that of "Guns, Germs and Steel". Except Diamond elaborated his bio-diversity-as-destinity view, but Harari focused on information - and the lack of information/communicating/learning between Inca and Aztec empires that lead to the huge gulf between the Inca and Pizarro. It is an interesting example on their difference.

Harari holds the view that we humans are so much weaker than other animals physically, and the only advantage that allowed us to roam the earth is our social skills. (Again, contrast this conviction with his statement that the more historians studied the past, the less certain of this outcome.) Other things equal, this view does make me to critically evaluate my interactions with other human beings -- am I too focused on tech details and not developing the critical, sapien-unique skill of socializing and gossiping? When I was shunning the office gossip and thought that I took the high road by focusing on my technical tasks, was I disadvantaged because sapiens inherently connect at the gossip level? This last part, is a blow to my self recognition. 
